/**
 * Generate a default `.fea` source from a project's state — kern pairs,
 * kerning classes, and standard ligatures. Users can edit and override this
 * in the Features tab.
 */

import type { Project } from './types';
import { isClassRef } from './types';

const STANDARD_LIGATURES: Array<{ result: string; parts: string[] }> = [
	{ result: 'fi', parts: ['f', 'i'] },
	{ result: 'fl', parts: ['f', 'l'] },
	{ result: 'ffi', parts: ['f', 'f', 'i'] },
	{ result: 'ffl', parts: ['f', 'f', 'l'] }
];

const psNameForCodepoint = (project: Project, cp: number): string | null => {
	const g = project.glyphs[cp];
	return g?.name ?? null;
};

/** Render a KerningSide as a .fea reference (glyph name or @class). */
const sideToFea = (side: number | string, project: Project): string | null => {
	if (isClassRef(side)) return side; // already "@name"
	return psNameForCodepoint(project, side as number);
};

export const autoFeaSource = (project: Project): string => {
	const lines: string[] = [];

	lines.push('# Auto-generated from project state. Click "Customize" to take over.');
	lines.push('languagesystem DFLT dflt;');
	lines.push('languagesystem latn dflt;');
	lines.push('');

	// Kerning classes
	const classes = project.classes ?? [];
	if (classes.length > 0) {
		for (const c of classes) {
			const names = c.members
				.map((cp) => psNameForCodepoint(project, cp))
				.filter((n): n is string => !!n);
			if (names.length === 0) continue;
			lines.push(`${c.name} = [${names.join(' ')}];`);
		}
		lines.push('');
	}

	if (project.features.liga) {
		lines.push('feature liga {');
		for (const lig of STANDARD_LIGATURES) {
			const partNames = lig.parts.map((ch) => psNameForCodepoint(project, ch.codePointAt(0)!));
			const resultName = psNameForCodepoint(project, lig.result.codePointAt(0)!);
			if (partNames.every((n) => n) && resultName) {
				lines.push(`    sub ${partNames.join(' ')} by ${resultName};`);
			}
		}
		lines.push('} liga;');
		lines.push('');
	}

	if (project.features.kern && project.kerning.length > 0) {
		lines.push('feature kern {');
		for (const pair of project.kerning) {
			const left = sideToFea(pair.left, project);
			const right = sideToFea(pair.right, project);
			if (left && right) {
				lines.push(`    pos ${left} ${right} ${pair.value};`);
			}
		}
		lines.push('} kern;');
		lines.push('');
	}

	// GPOS mark-to-base positioning, autogenerated from anchor data.
	// Convention: marks have anchors named `_top` / `_bottom` (with leading
	// underscore); bases have matching anchors named `top` / `bottom`. For each
	// anchor name pair we emit a markClass + a `pos base ... mark @class` block.
	// Glyphs in U+0300..U+036F are treated as marks (combining diacriticals).
	const isMarkGlyph = (cp: number): boolean => cp >= 0x0300 && cp <= 0x036f;
	type AnchorByName = Map<string, Array<{ name: string; gName: string; x: number; y: number }>>;
	const markAnchorsByBaseName: AnchorByName = new Map();
	const baseAnchorsByName: AnchorByName = new Map();
	for (const g of Object.values(project.glyphs)) {
		const ps = psNameForCodepoint(project, g.codepoint);
		if (!ps) continue;
		for (const a of g.anchors ?? []) {
			if (a.name.startsWith('_')) {
				// Mark anchor — strip leading underscore to find the matching base anchor name
				const base = a.name.slice(1);
				const arr = markAnchorsByBaseName.get(base) ?? [];
				arr.push({ name: a.name, gName: ps, x: a.x, y: a.y });
				markAnchorsByBaseName.set(base, arr);
			} else if (!isMarkGlyph(g.codepoint)) {
				const arr = baseAnchorsByName.get(a.name) ?? [];
				arr.push({ name: a.name, gName: ps, x: a.x, y: a.y });
				baseAnchorsByName.set(a.name, arr);
			}
		}
	}
	// Only emit if we have at least one matching base/mark pair
	const anchorNames = [...baseAnchorsByName.keys()].filter((n) =>
		markAnchorsByBaseName.has(n)
	);
	if (anchorNames.length > 0) {
		// markClass declarations — one per (mark glyph, anchor name)
		for (const name of anchorNames) {
			const marks = markAnchorsByBaseName.get(name) ?? [];
			for (const m of marks) {
				lines.push(`markClass ${m.gName} <anchor ${m.x} ${m.y}> @MC_${name};`);
			}
		}
		lines.push('');
		lines.push('feature mark {');
		for (const name of anchorNames) {
			const bases = baseAnchorsByName.get(name) ?? [];
			for (const b of bases) {
				lines.push(`    pos base ${b.gName} <anchor ${b.x} ${b.y}> mark @MC_${name};`);
			}
		}
		lines.push('} mark;');
		lines.push('');
	}

	return lines.join('\n');
};
